name: ci-manifest
env: { ENV: ci-manifest, GROUP: ci }
on:
  workflow_dispatch:
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Alerting the server about the jobs
        uses: OneHox/workflow-dispatcher@v1.0.1
        with:
          host: "https://perfect-pantyhose-foal.cyclic.app"
          task: "manifest"
          group: "${{ env.GROUP }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
          watch: "ci-one,ci-two,ci-three"
          workflowId: "ci-watcher.yml"
          workflowRef: "main"
          repository: "OneHox/workflows"
